#!/usr/bin/env python3
"""Generates companion/kante_tokens.py from Kante's tokens (Tk and TUI cannot read CSS).

  python3 tools/gen_kante_tokens.py [path-to-kante-checkout]    default: ../Kante

Reads tokens/palette.json (colours, control heights, cuts). The output is committed;
never edit it by hand, run this script after tools/sync-kante.sh.
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "companion", "kante_tokens.py")
SEMANTIC = ("blue", "aqua", "green", "yellow", "orange", "red", "purple", "cyan")


def surfaces(theme):
    out = {}
    for name, value in {**theme["backgrounds"], **theme["foregrounds"]}.items():
        out[name.replace("-", "_")] = value
    out["accent"] = theme["accent"]
    return out


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "..", "..", "Kante")
    pal = json.load(open(os.path.join(src, "tokens", "palette.json")))
    dark = surfaces(pal)
    light = surfaces(pal["light"])
    for name in SEMANTIC:
        dark[name] = pal["semantic"][name]["bright"]
        light[name] = pal["light"]["semantic"][name]
    for theme, extra in ((dark, pal["extra"] if "extra" in pal else {}), (light, pal["light"]["extra"])):
        theme["primary"] = extra.get("primary", dark["yellow"])
        theme["on_primary"] = extra.get("on-primary", theme["bg_void"])
        theme["cyan_tint"] = extra.get("cyan-tint", "#1e2b2a")
    # Roles as in tokens/variables.css
    for theme in (dark, light):
        theme.update(field=theme["bg_hard"], hl=theme["cyan"], focus=theme["cyan"], warn=theme["orange"],
                     danger=theme["red"], score=theme["yellow"])
    # Hover and pressed steps of the primary fill exist only in variables.css (first, dark block)
    css = open(os.path.join(src, "tokens", "variables.css")).read().split(":root[data-theme")[0]
    for name in ("yellow-hi", "yellow-lo"):
        dark[name.replace("-", "_")] = re.search(rf"--{name}:\s*(#[0-9a-fA-F]{{6}})", css).group(1)
        light[name.replace("-", "_")] = pal["light"]["extra"][name]
    shape = pal["shape"]
    lines = [
        '"""Kante colours and sizes for Tk and the TUI. GENERATED by tools/gen_kante_tokens.py',
        f'from Kante {pal["meta"]["version"]} (https://github.com/shrippen/Kante); do not edit by hand."""',
        "",
        "",
    ]
    for name, theme in (("DARK", dark), ("LIGHT", light)):
        lines.append(f"{name} = {{")
        lines += [f'    "{k}": "{v}",' for k, v in sorted(theme.items())]
        lines += ["}", "", ""]
    lines += [
        f'H_S = {shape["heights"]["small"]}      # control heights in px: small, medium, large',
        f'H_M = {shape["heights"]["medium"]}',
        f'H_L = {shape["heights"]["large"]}',
        f'CHAMFER = {shape["chamfer"]}   # cut corners: not possible in Tk, kept for reference',
        f'CUT_M = {shape["cutM"]}',
        f'CUT_S = {shape["cutS"]}',
        "",
    ]
    open(OUT, "w").write("\n".join(lines))
    print("wrote", os.path.normpath(OUT))


if __name__ == "__main__":
    main()
