#!/usr/bin/env bash
# Copies the Kante web build into the Companion (vendored, so the UI works offline).
#   tools/sync-kante.sh [path-to-kante-checkout]     default: ../Kante
# Takes docs/v1/shrippen.css and shrippen.js unchanged plus the fonts from fonts/,
# writes fonts.css (Kante's stylesheet has no @font-face) and VERSION.
set -euo pipefail
SRC="${1:-$(dirname "$0")/../../Kante}"
DST="$(cd "$(dirname "$0")/.." && pwd)/companion/static/vendor"
VER="$(python3 -c "import json,sys;print(json.load(open(sys.argv[1]))['meta']['version'])" "$SRC/tokens/palette.json")"
FONTS=(Rajdhani-500 Rajdhani-600 Rajdhani-700 JetBrainsMono-400 JetBrainsMono-500)

[ -f "$SRC/docs/v1/shrippen.css" ] || { echo "no Kante build in $SRC (run ./build.sh there)" >&2; exit 1; }
mkdir -p "$DST/fonts"
rm -f "$DST/styles.css" "$DST/SOURCE.md"
cp "$SRC/docs/v1/shrippen.css" "$SRC/docs/v1/shrippen.js" "$DST/"

: > "$DST/fonts.css"
for f in "${FONTS[@]}"; do
  cp "$SRC/fonts/$f.ttf" "$DST/fonts/"
  family="${f%-*}"; weight="${f##*-}"
  [ "$family" = JetBrainsMono ] && family="JetBrains Mono"
  echo "@font-face{font-family:'$family';font-weight:$weight;font-display:swap;src:url(fonts/$f.ttf) format('truetype')}" >> "$DST/fonts.css"
done
cp "$SRC/fonts/OFL.txt" "$DST/fonts/"

{
  echo "Kante $VER (web build, vendored unchanged)"
  echo "source: https://github.com/shrippen/Kante"
  echo "branch: $(git -C "$SRC" branch --show-current)"
  echo "commit: $(git -C "$SRC" rev-parse HEAD)"
  echo "files:  shrippen.css shrippen.js fonts/ (fonts.css is generated by tools/sync-kante.sh)"
  echo "Do not edit; Kader-specific layout goes in ../app.css. Update: tools/sync-kante.sh"
} > "$DST/VERSION"
echo "synced Kante from $SRC"
