"""Kante colours and sizes for Tk and the TUI. GENERATED by tools/gen_kante_tokens.py
from Kante 1.9.0 (https://github.com/shrippen/shrippen.github.io); do not edit by hand."""


DARK = {
    "accent": "#e8dcc4",
    "aqua": "#8ec07c",
    "bg0": "#282828",
    "bg1": "#3c3836",
    "bg2": "#504945",
    "bg_hard": "#1d2021",
    "bg_panel": "#2a2826",
    "bg_void": "#141312",
    "blue": "#83a598",
    "cyan": "#5ccfc4",
    "cyan_tint": "#1e2b2a",
    "danger": "#fb4934",
    "fg0": "#fbf1c7",
    "fg1": "#ebdbb2",
    "fg2": "#d5c4a1",
    "fg3": "#a89984",
    "field": "#1d2021",
    "focus": "#5ccfc4",
    "green": "#b8bb26",
    "hl": "#5ccfc4",
    "on_primary": "#141312",
    "orange": "#fe8019",
    "primary": "#fabd2f",
    "purple": "#d3869b",
    "red": "#fb4934",
    "score": "#fabd2f",
    "warn": "#fe8019",
    "yellow": "#fabd2f",
    "yellow_hi": "#fdc94a",
    "yellow_lo": "#e5a823",
}


LIGHT = {
    "accent": "#3c3836",
    "aqua": "#427b58",
    "bg0": "#f0e9d6",
    "bg1": "#fbf8ee",
    "bg2": "#d3c8ac",
    "bg_hard": "#e6dec6",
    "bg_panel": "#f7f2e4",
    "bg_void": "#f0e9d6",
    "blue": "#076678",
    "cyan": "#0f6b66",
    "cyan_tint": "#d9ebe4",
    "danger": "#9d0006",
    "fg0": "#282828",
    "fg1": "#3c3836",
    "fg2": "#665c54",
    "fg3": "#6a5f52",
    "field": "#e6dec6",
    "focus": "#0f6b66",
    "green": "#4f5d0a",
    "hl": "#0f6b66",
    "on_primary": "#141312",
    "orange": "#af3a03",
    "primary": "#fabd2f",
    "purple": "#8f3f71",
    "red": "#9d0006",
    "score": "#8a5a00",
    "warn": "#af3a03",
    "yellow": "#8a5a00",
    "yellow_hi": "#fcc845",
    "yellow_lo": "#e5a823",
}


H_S = 32      # control heights in px: small, medium, large
H_M = 40
H_L = 48
CHAMFER = 16   # cut corners: not possible in Tk, kept for reference
CUT_M = 10
CUT_S = 6
